### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA


###
PATCH http://localhost:8080/api/users/123/password
Content-Type: application/json
//cambiar contraseña

{
  "old_password": "233455665",
  "new_password": "3435555555"
}

###
PUT http://localhost:8080/api/users/123/host
Content-Type: application/json
//añadir descripcion y/o documentos legales

{
 "description": "10 años en la industria",
  "legal_documents": [
    "https://cdn.example.com/docs/id_frontal.pdf",
    "https://cdn.example.com/docs/id_reverso.pdf"
  ]
}

###
POST http://localhost:8080/api/auth/login
Content-Type: application/json
// login

{
  "email": "samuelo@gmail.com",
  "password": "perroGato123"
}

> {% client.global.set("token", response.body.message.token); %}

###
PATCH http://localhost:8080/api/auth/recover
Content-Type: application/json
//cambiar contraseña olvidada

{
  "email": "samuel@gmail.com",
  "code": "123456",
  "new_password": "samuelo1234"
}

###
POST http://localhost:8080/api/auth
Content-Type: application/json
//registrarse

{
  "name": "samuel",
  "surname": "andres",
  "email": "samuelo@gmail.com",
  "phone": "31934232",
  "birthDate": "2005-02-23",
  "password": "perroGato123",
  "photoUrl": "dfdsfdsfsdfsdfs",
  "country": "colombia",
  "role": "HOST"
}

###
GET http://localhost:8080/api/users/list
//devuelve una lista de todos los usuarios

###
PUT http://localhost:8080/api/users/12
Content-Type: application/json
//editar datos del usuario

{
  "name": "samuel",
  "phone": "31932404",
  "photoUrl": "/mnt/data/ff6a4b1e-5eda-40ec-8903-aeaaa1ae0b83.png"
}

###
DELETE http://localhost:8080/api/users/12
Content-Type: application/json
//eliminar usuario

{
  "password": "234565"
}

###
POST http://localhost:8080/api/bookings/12
Content-Type: application/json
//crear una reserva

{
  "check_in": "2025-09-30T14:00:00",
  "check_out": "2025-10-15T11:30:00",
  "guest_number": 2
}


###
GET http://localhost:8080/api/users/12/bookings
Content-Type: application/json
// ver el listado de reservas aplicando filtros

{
  "bookingState": "COMPLETED",
  "checkIn": "2025-09-14T14:00:00",
  "checkOut": "2025-09-15T11:30:00",
  "guest_number": 2
}

###
DELETE http://localhost:8080/api/bookings/12
//eliminar cancelar reserva

###
GET http://localhost:8080/api/accommodations/12/bookings
Content-Type: application/json
// ver el listado de reservas que tiene el alojamiento

{
  "bookingState": "CONFIRMED",
  "checkIn": "2025-09-14T14:00:00",
  "checkOut": "2025-09-16T11:30:00",
  "guest_number": 2
}

###
GET http://localhost:8080/api/accommodations/0
Content-Type: application/json
// buscar alojamientos disponibles

{
  "city": "Barranquilla",
  "checkIn": "2025-12-01T15:00:00",
  "checkOut": "2025-12-05T11:00:00",
  "guest_number": 4
}

###
POST http://localhost:8080/api/accommodations
Content-Type: application/json
Authorization: Bearer {{token}}
// Crear un alojamiento

{
  "title": "Casa en la playa",
  "description": "Hermosa casa frente al mar, equipada con todas las comodidades para unas vacaciones inolvidables. Incluye piscina, terraza y acceso directo a la playa.",
  "price": 150.0,
  "picsUrl": [
    "https://example.com/foto1.jpg",
    "https://example.com/foto2.jpg"
  ],
  "accommodationType": "HOUSE",
  "capacity": 6,
  "country": "Colombia",
  "department": "Atlántico",
  "city": "Barranquilla",
  "neighborhood": "Prado",
  "street": "Calle 84 #45-32",
  "postalCode": "AB12CD34",
  "amenities": [
    "WIFI"
  ],
  "latitude": 10.9685,
  "longitude": -74.7813
}

###
PUT http://localhost:8080/api/accommodations/5a552401-8b34-4d25-90a6-ba939ebd74ff
Content-Type: application/json
Authorization: Bearer ...
//actualizar, editar alojamiento

{
  "title": "Casa Bonita",
  "description": "Una hermosa casa ubicada cerca del centro de la ciudad, con amplios espacios y todas las comodidades necesarias para una estadía confortable.",
  "capacity": 4,
  "price": 120.5,
  "country": "Colombia",
  "department": "Cundinamarca",
  "city": "Bogotá",
  "neighborhood": "Chapinero",
  "street": "Carrera 7 #45-67",
  "postalCode": "AB1234",
  "pics_url": [
    "https://example.com/img1.jpg",
    "https://example.com/img2.jpg"
  ],
  "amenities": [
    "WIFI"
  ],
  "accommodationType": "HOUSE"
}

###
DELETE http://localhost:8080/api/accommodations/8d02c6c0-58bb-49c4-92e0-76f16a584570
// eliminar un alojamiento (cambiar su estado)

###
GET http://localhost:8080/api/users/12/accommodations/host
// lista los alojamientos del cliente

###
GET http://localhost:8080/api/accommodations/12/amenities
// lista de todos los servicios del alojamiento

###
GET http://localhost:8080/api/accommodations/12/comments
// lista de todos los comentarios del alojamiento

###
POST http://localhost:8080/api/accommodations/12/comments
Content-Type: application/json
// crear un comentario a un alojamiento (reserva stado == finalizada)

{
  "comment": "muy bonita la finca",
  "rating": 5
}

###
POST http://localhost:8080/api/comments/12
Content-Type: application/json
//reponder un comentario

{
  "reply": "gracias"
}

###
GET http://localhost:8080/api/accommodations/12/stats
// ver estadisticas del alojamiento







